config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/help'

  root 'static_pages#home'

  get 'rooms/show_active'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  resources :users
  resources :sessions
  resources :students
  resources :patients
  resources :rooms do
    put "connected", :to => "rooms#connected", as: :connected
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
	belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  has_one :student
  has_one :patient
  has_one :room
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "hello world"
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def index
		@patients = Patient.paginate(:page => params[:page], :per_page => 3)
	end

	def new
	  @patient = Patient.new
	end

    def create
  	  current_user.create_patient(patient_params)
  	  redirect_to static_pages_home_path
    end

    private
    def patient_params
      params.require(:patient).permit(:name)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	require "opentok"
	$session

	def index
		@rooms = Room.order("created_at DESC")
		@new_room = Room.new()
	end

	def create
		@api_key = ENV['API_KEY']
    	opentok = OpenTok::OpenTok.new(ENV["API_KEY"], ENV["API_SECRET"])
    	session = opentok.create_session
    	params[:room][:session_id] = session.session_id
    	respond_to do |format|
          if current_user.create_room(room_params)
      	    format.html { redirect_to '/rooms/#{@new_room.id}'}
          #redirect_to rooms_party_path
          else
            format.html { render :controller => 'rooms', :action => "index" }
          end
        end
	end

	def show
	    @api_key = ENV['API_KEY']
		opentok = OpenTok::OpenTok.new(ENV["API_KEY"], ENV["API_SECRET"])
		@room = Room.find(params[:id])
		@token = opentok.generate_token(@room.session_id)
	end

	def show_active
        @active_rooms = Room.where(connected: true)
	end

	def connected
	    @room = Room.find params[:room_id]
	    @room.update_attributes(:connected => params[:room][:connected])
	end

    private
    def room_params
      @room_params = params.require(:room).permit(:id, :name, :session_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.paginate(:page => params[:page], :per_page => 3)
	end

	def new
	  @student = Student.new
	end

    def create
  	  current_user.create_student(student_params)
  	  redirect_to new_room_path
    end

    private
    def student_params
      params.require(:student).permit(:name, :grade)
    end
    def room_params
      params.require(:room).permit(:id, :name, :session_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	  @user = User.new
	end

    def create
	  @user = User.new(params.require(:user).permit!)
	  if @user.save
	    session[:user_id] = @user.id
		Rails.logger.debug("My object: #{@user.inspect}")
		if @user.isstudent
			puts "Redirecting to student form"
			redirect_to new_student_path
		else
			puts "Redirecting to care form"
			redirect_to new_patient_path
		end
	    #redirect_to users_path, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end


	def show
		@users = User.all
	end
	
	private

	def user_params
      params.require(:user).permit(:id, :username, :email, :password, :password_confirmation, :isstudent)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goldenyears</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">GoldenYears</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
            <a class="nav-link" href="/static_pages/home">Home</a>
          </li>
          <li class="nav-item">
            <% if current_user %>
                <a class="nav-link" href="/log_out"> <%= current_user.email %> Logout</a>
            <% else %>
                <a class="nav-link" href="/log_in">Login</a>
  	        <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<%= link_to "Active Rooms", rooms_show_active_path %>

app/views/patients/index_old_skype_api.html.erb
<script type="text/javascript" src="https://secure.skypeassets.com/i/scom/js/skype-uri.js"></script>

<% @patients.each do |patient| %>
  <div class="booyah-box">
    <h1><%= patient.name %></h1><br />
    <i><%= patient.skypeid %></i><br /><br />
     <div id= <%= "SkypeButton_Call_"+patient.name %>>
        <script type="text/javascript">
          Skype.ui({
                 "name": "call",
                 "element": "<%= "SkypeButton_Call_"+patient.name %>",
                 "participants": ["<%= patient.skypeid %>"]
                });
        </script>
    </div>
  </div>

  <hr />
<% end %>

app/views/patients/new.html.erb
  <%= form_for @patient do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %><br />

    <%= f.submit 'Create' %>
  <% end %>

app/views/rooms/index.html.erb
<fieldset>
  <table class="table">
    <thead  >
        <tr>
            <th class="text-center">Click Button</th>
        </tr>
    </thead>
    <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td align="center">
                <div class="btn btn-primary">
                    <%= link_to room.name, room_path(room) %>
                </div>
            </td>
          </tr>
        <% end %>
    </tbody>
  </table>
</fieldset>

app/views/rooms/new.html.erb
<div class="row justify-content-center align-items-center h-100" id="newRoom">
  <fieldset>
    <legend>Create a new room</legend>
    <%= form_for Room.new do |f| %>
      Room Name: <%= f.text_field :name %><br/><br/>
      <%= f.submit %>
    <% end %>
  </fieldset>
</div>

app/views/rooms/show.html.erb
<script type="text/javascript">
    var apiKey = '<%= @api_key %>';
    var sessionId = '<%= @room.session_id %>';
    var token = '<%= @token %>';
    var room = '<%= @room %>';
</script>

<button class="btn btn-primary" onclick="disconnectSession()">Disconnect</button>

<div id="videos" class="row">
    <div class="col-md-4">
        <div class="embed-responsive embed-responsive-16by9">
            <div id="publisher" class="embed-responsive-item"></div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="embed-responsive embed-responsive-16by9">
            <div id="subscriber" class="embed-responsive-item"></div>
        </div>
    </div>

</div>

<input type="text" id="connectionCountField" value="0"></input>
<input type="hidden" name="_method" value="put" />
<script>
    // Handling all of our errors here by alerting them
    function handleError(error) {
      if (error) {
        alert(error.message);
      }
    }
    var session;
    var connection_id;
    var connectionCount;
    var room_id = <%= @room.id %>
    console.log("room id: ", room_id)

    initializeSession();

    function disconnectSession() {
        session.disconnect();
    }

    function initializeSession() {
      session = OT.initSession(apiKey, sessionId);

      // Subscribe to a newly created stream
      session.on('streamCreated', function(event) {
        console.log("session on")
        var subscriberContainer = document.getElementById('subscriber');
        session.subscribe(event.stream, subscriberContainer, {
          insertMode: 'append',
          width: '100%',
          height: '100%'
        }, handleError);
      });

      // Create a publisher
      var publisher = OT.initPublisher('publisher', {
        insertMode: 'append',
        width: '100%',
        height: '100%'
      }, handleError);

      // Connect to the session
      session.connect(token, function(error) {
          // If the connection is successful, publish to the session
          console.log("session connected")
          if (error) {
            handleError(error);
          } else {
            session.publish(publisher, handleError);
          }
      });

      session.on("connectionCreated", function(event) {
          console.log("connectionCreated");
           $.ajax({
                    type: "PUT",
                    data: JSON.stringify({ room: {connected: true}, _method:'put' }),
                    url: "/rooms/" + room_id + "/connected",
                    contentType: 'application/json'
                  }).done(function( msg ){
                    // alert( "Data Saved: " + msg );
           });
       });

      // Disconnect
      session.on('sessionDisconnected', function(event) {
        console.log("session Disconnected")
        $.ajax({
                type: "PUT",
                data: JSON.stringify({ room: {connected: false}, _method:'put' }),
                url: "/rooms/" + room_id + "/connected",
                contentType: 'application/json'
                }).done(function( msg ){
                    window.location.replace('<%= rooms_path %>');
                    // alert( "Data Saved: " + msg );
           });

      });

      session.on("connectionDestroyed", function(event){
          console.log("connectionDestroyed");
           $.ajax({
                    type: "PUT",
                    data: JSON.stringify({ room: {connected: false}, _method:'put' }),
                    url: "/rooms/" + room_id + "/connected",
                    contentType: 'application/json'
                  }).done(function( msg ){
                    // alert( "Data Saved: " + msg );
           });
      });
    }

    function displayConnectionCount(){
        document.getElementById("connectionCountField").value = connectionCount.toString();
    }
</script>

app/views/rooms/show_active.html.erb
<fieldset>
  <legend>Existing Conference</legend>
  <table cellpadding="2" cellspacing="5">
    <tr>
      <th>Name</th>
      <th>Started</th>
    </tr>

    <% @active_rooms.each do |room| %>
      <tr>
        <td align="center" width="300px"><%= link_to room.name, room_path(room) %> </td>
        <td><%= room.created_at %></td>
      </tr>
    <% end %>
  </table>
</fieldset>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1 class="text-center"> Walk through Video with steps to use this site</h1>
<div class="booyah-box" class="row justify-content-center align-items-center h-100">
      <% if current_user %>
        <center><%= link_to_if current_user.isstudent, "Connect Now",  rooms_path do
          link_to "Connect Now", rooms_show_active_path
        end 
        %></center>
      <% else %>
    	<%= link_to "log in", log_in_path %>
  	  <% end %>
</div>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="..." alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="..." alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="..." alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<p class="text-center"> Slideshow for dementia care and prevention tips </p>

app/views/students/index.html.erb
<% @students.each do |student| %>
  <div>
    <h1><%= student.name %></h1><br />
    <p><%= student.grade %></p><br /><br />
<% end %>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @students, :container => false %>
 </div>

app/views/students/index_hg_2.html.erb
<% @students.each do |student| %>
  <div>
    <h1><%= student.name %></h1><br />
    <i><%= student.skypeid %></i><br /><br />
    <p><%= student.grade %></p><br /><br />
	<g:hangout render="createhangout"
        invites="[{ id : 'manjari.infinite@gmail.com', invite_type : 'EMAIL' }]">
    </g:hangout>
<% end %>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @students, :container => false %>
 </div>

<script src="https://apis.google.com/js/platform.js" async defer></script>

app/views/students/index_skype.html.erb
<% @students.each do |student| %>
  <div>
    <h1><%= student.name %></h1><br />
    <i><%= student.skypeid %></i><br /><br />
    <p><%= student.grade %></p><br /><br />
	<span class="skype-button rounded" data-contact-id="<%= student.skypeid %>"></span>
<% end %>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @students, :container => false %>
 </div>

 <script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js">
 </script>

app/views/students/index_tokbox.html.erb
<% @students.each do |student| %>
  <div>
    <h1><%= student.name %></h1><br />
    <i><%= student.skypeid %></i><br /><br />
    <p><%= student.grade %></p><br /><br />
	<div id="otEmbedContainer" style="width:800px; height:640px"></div>
<% end %>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @students, :container => false %>
 </div>
                  
<script src="https://tokbox.com/embed/embed/ot-embed.js?embedId=5d5d85bb-a2ad-41cf-b0fc-a6d8ebf4bae8&room=DEFAULT_ROOM"></script>

app/views/students/new.html.erb
<div class="row justify-content-center align-items-center h-100">
  <%= form_for @student do |f| %>
    <%= f.label :name %>:
    <%= f.text_field :name %><br />
    
    <%= f.label :grade %>:
    <%= f.text_field :grade %><br />
    <%= f.submit 'Create' %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1> Show all the users </h1>

app/views/users/new.html.erb
<h1 class="text-center">Sign Up</h1>

<div class="row justify-content-center align-items-center h-100">
    <%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
      </p>
      <p>
        <b>Are you a student?</b><br />
        <%= label :isstudent, "Yes", value: false %>
        <%= f.radio_button :isstudent, true, :value => true %>
        <%= label :isstudent, "No", value: false %>
        <%= f.radio_button :isstudent, false, :value => false %>
      </p>
      <p class="button"><%= f.submit %></p>
    <% end %>
</div>